services:
  backend:
    image: email-handler-backend
    ports:
      - '3001:3001'
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0.4
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'admin'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    volumes:
      - ./mongo-volume:/data/db