version: '3.8'
services:
  prod:
    container_name: email-service-prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - "3001:3001" # application port
      - "9229:9229" # debugger port
    networks:
      - email-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env

networks:
  email-service: