FROM node:lts-alpine3.15 AS builder
USER node

ENV NODE_ENV build

WORKDIR /home/node

COPY --chown=node:node _email-service/drop/package*.json ./
RUN npm ci

COPY --chown=node:node _email-service/drop/. .
RUN npm run build && npm prune --production
  
  # ---

FROM node:lts-alpine3.15 AS production

ENV NODE_ENV production

USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist ./dist/

CMD ["npm", "run", "start:prod"]
